[package]
name = "rusty_ytdl"
version = "0.1.0"
authors = ["Mithronn"]
edition = "2021"
description = "A Rust library for Youtube video downloader"
repository = "https://github.com/Mithronn/rusty-ytdl"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = {version = "0.11.5"}
scraper = "0.12.0"
serde = "1.0.152"
serde_json = "1.0.94"
serde_qs = "0.10.1"
regex = "1.6.0"
url = "2.3.1"
js-sandbox = "0.1.6"
urlencoding = "2.1.2"
lazy_static = "1.4.0"
xml_oxide = "0.3.0"

[dev-dependencies]
tokio = { version = "1.26.0", features = ["macros", "signal","rt-multi-thread"] }
