[package]
name = "rusty_ytdl"
version = "0.3.0"
authors = ["Mithronn"]
edition = "2021"
description = "A Rust library for Youtube video downloader"
repository = "https://github.com/Mithronn/rusty-ytdl"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["youtube", "downloader", "ytdl", "youtube-dl"]
include = [
    "src/**/*", "Cargo.toml",
]
exclude = [
    "examples/**/*",
    "tests/**/*",
]

[package.metadata.docs.rs]
all-features = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = {version = "0.11.14", features = ["cookies"]}
scraper = "0.12.0"
serde = "1.0.152"
serde_json = "1.0.94"
serde_qs = "0.10.1"
regex = "1.6.0"
url = "2.3.1"
js-sandbox = "0.1.6"
urlencoding = "2.1.2"
xml_oxide = "0.3.0"
thiserror = "1.0.39"
derive_more = "0.99.17"
derivative = "2.2.0"
once_cell = "1.17.1"
tokio = { version = "1.26.0", optional = true }

[dev-dependencies]
tokio = { version = "1.26.0", features = ["full"] }

[features]
blocking = ["tokio/rt", "tokio/rt-multi-thread"]
