[package]
name = "rust-ytdl-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = { version = "1.1.0" }
tokio = { version = "1.21.2", features = ["full"] }
tokio-stream = "0.1.11"
reqwest = {version = "0.11.5", features = ["blocking","stream"]}
scraper = "0.12.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_qs = "0.10.1"
regex = "1.6.0"
url = "2.3.1"
js-sandbox = "0.1.6"
urlencoding = "2.1.2"